services:
  - type: web
    name: architectural-space-analyzer
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: dwg-analyzer-db
          property: connectionString
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    
databases:
  - name: dwg-analyzer-db
    databaseName: dwg_analyzer_pro
    user: de_de
    plan: starter